name: Deploy Node.js app to Azure Web App - Opinionserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        
    - name: Install server dependencies
      run: |
        cd server
        npm install
        
    # Note: No build step as per your requirement

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Opinionserver'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EEB25FEC3F4E453DB45ECBBF8DE5A8AB }}
        package: server/  # Specify the server folder for deployment
